# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui
import pyqtgraph as pg
from pyqtgraph import PlotWidget, GraphicsWidget


class CustomViewBox(pg.ViewBox):
    def __init__(self, *args, **kwds):
        pg.ViewBox.__init__(self, *args, **kwds)
        self.setMouseMode(self.RectMode)

    # reimplement right-click to zoom out
    def mouseClickEvent(self, ev):
        if ev.button() == QtCore.Qt.RightButton:
            pass

    def mouseDragEvent(self, ev):
        if ev.button() == QtCore.Qt.RightButton:
            pass

    def wheelEvent(self, event):
        print "Wheel event working"


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        vb = CustomViewBox()
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1366, 684)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))

        self.plot = PlotWidget(parent=self.centralwidget, viewBox=vb)
        self.plot.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        self.plot.setMinimumSize(QtCore.QSize(1000, 600))
        self.plot.setMaximumSize(QtCore.QSize(1000, 600))
        self.plot.setObjectName(_fromUtf8("plot"))

        '''
        Readout panel below oscilloscope screen.
        '''
        self.readout_frame = QtGui.QFrame(self.centralwidget)
        self.readout_frame.setGeometry(QtCore.QRect(0, 620, 1000, 43))
        self.readout_frame.setStyleSheet(_fromUtf8("background-color: #000;\n"
                                                   ""))
        self.readout_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.readout_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.readout_frame.setObjectName(_fromUtf8("readout_frame"))

        font = QtGui.QFont()
        font.setPointSize(12)

        self.readout_special_one = QtGui.QLabel(self.readout_frame)
        self.readout_special_one.setFont(font)
        self.readout_special_one.setGeometry(QtCore.QRect(800, 0, 200, 22))
        self.readout_special_one.setStyleSheet(_fromUtf8("background-color: #000; color: #0F0;"))
        self.readout_special_one.setObjectName(_fromUtf8("readout_special_one"))

        self.readout_special_two = QtGui.QLabel(self.readout_frame)
        self.readout_special_two.setFont(font)
        self.readout_special_two.setGeometry(QtCore.QRect(800, 22, 200, 22))
        self.readout_special_two.setStyleSheet(_fromUtf8("background-color: #000; color: #0F0;"))
        self.readout_special_two.setObjectName(_fromUtf8("readout_special_two"))

        self.readout_one = QtGui.QLabel(self.readout_frame)
        self.readout_one.setFont(font)
        self.readout_one.setGeometry(QtCore.QRect(0, 0, 200, 22))
        self.readout_one.setStyleSheet(_fromUtf8("background-color: #000; color: #FF0;"))
        self.readout_one.setObjectName(_fromUtf8("readout_one"))

        self.readout_two = QtGui.QLabel(self.readout_frame)
        self.readout_two.setFont(font)
        self.readout_two.setGeometry(QtCore.QRect(0, 22, 200, 22))
        self.readout_two.setStyleSheet(_fromUtf8("background-color: #000; color: #FF0;"))
        self.readout_two.setObjectName(_fromUtf8("readout_two"))

        self.readout_three = QtGui.QLabel(self.readout_frame)
        self.readout_three.setFont(font)
        self.readout_three.setGeometry(QtCore.QRect(200, 0, 200, 22))
        self.readout_three.setStyleSheet(_fromUtf8("background-color: #000; color: #FF0;"))
        self.readout_three.setObjectName(_fromUtf8("readout_three"))

        self.readout_four = QtGui.QLabel(self.readout_frame)
        self.readout_four.setFont(font)
        self.readout_four.setGeometry(QtCore.QRect(200, 22, 200, 22))
        self.readout_four.setStyleSheet(_fromUtf8("background-color: #000; color: #FF0;"))
        self.readout_four.setObjectName(_fromUtf8("readout_four"))

        self.readout_five = QtGui.QLabel(self.readout_frame)
        self.readout_five.setFont(font)
        self.readout_five.setGeometry(QtCore.QRect(400, 0, 200, 22))
        self.readout_five.setStyleSheet(_fromUtf8("background-color: #000; color: #F00;"))
        self.readout_five.setObjectName(_fromUtf8("readout_five"))

        self.readout_six = QtGui.QLabel(self.readout_frame)
        self.readout_six.setFont(font)
        self.readout_six.setGeometry(QtCore.QRect(400, 22, 200, 22))
        self.readout_six.setStyleSheet(_fromUtf8("background-color: #000; color: #F00;"))
        self.readout_six.setObjectName(_fromUtf8("readout_six"))

        self.readout_seven = QtGui.QLabel(self.readout_frame)
        self.readout_seven.setFont(font)
        self.readout_seven.setGeometry(QtCore.QRect(600, 0, 200, 22))
        self.readout_seven.setStyleSheet(_fromUtf8("background-color: #000; color: #F00;"))
        self.readout_seven.setObjectName(_fromUtf8("readout_seven"))

        self.readout_eight = QtGui.QLabel(self.readout_frame)
        self.readout_eight.setFont(font)
        self.readout_eight.setGeometry(QtCore.QRect(600, 22, 200, 22))
        self.readout_eight.setStyleSheet(_fromUtf8("background-color: #000; color: #F00;"))
        self.readout_eight.setObjectName(_fromUtf8("readout_eight"))

        self.horizontal_scroll_bar = QtGui.QScrollBar(self.centralwidget)
        self.horizontal_scroll_bar.setGeometry(QtCore.QRect(0, 600, 1000, 20))
        self.horizontal_scroll_bar.setMinimumSize(QtCore.QSize(1000, 20))
        self.horizontal_scroll_bar.setMaximumSize(QtCore.QSize(1000, 20))
        self.horizontal_scroll_bar.setStyleSheet(_fromUtf8("background-color: #88B;"))
        self.horizontal_scroll_bar.setMinimum(-90)
        self.horizontal_scroll_bar.setMaximum(90)
        self.horizontal_scroll_bar.setProperty("value", 0)
        self.horizontal_scroll_bar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontal_scroll_bar.setObjectName(_fromUtf8("horizontal_scroll_bar"))

        '''
        Channel control.
        '''
        self.channel_control_box = QtGui.QGroupBox(self.centralwidget)
        self.channel_control_box.setGeometry(QtCore.QRect(1005, 135, 230, 521))
        self.channel_control_box.setStyleSheet(_fromUtf8(""))
        self.channel_control_box.setObjectName(_fromUtf8("channel_control_box"))

        '''
        CHANNEL 1.
        '''
        self.channel_one_box = QtGui.QGroupBox(self.channel_control_box)
        self.channel_one_box.setGeometry(QtCore.QRect(10, 20, 211, 240))
        self.channel_one_box.setObjectName(_fromUtf8("channel_one_box"))
        self.ch1_checkbox = QtGui.QCheckBox(self.channel_one_box)
        self.ch1_checkbox.setGeometry(QtCore.QRect(10, 20, 140, 20))
        self.ch1_checkbox.setObjectName(_fromUtf8("ch1_checkbox"))
        self.ch1_checkbox.setChecked(True)
        self.ch1_checkbox.setStyleSheet(_fromUtf8("background-color: #fafa00;\n"
                                                  "border: 1px solid #000;\n"
                                                  "border-radius: 3px;\n" "padding: 30px 0 30px 5px;"))
        self.vpos_one_frame = QtGui.QFrame(self.channel_one_box)
        self.vpos_one_frame.setGeometry(QtCore.QRect(10, 50, 81, 181))
        self.vpos_one_frame.setStyleSheet(_fromUtf8("background-color: #eef;\n"
                                                    "border: 1px solid #888;\n"
                                                    "border-radius: 5px;"))
        self.vpos_one_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.vpos_one_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.vpos_one_frame.setObjectName(_fromUtf8("vpos_one_frame"))
        self.vpos_one_top_label = QtGui.QLabel(self.vpos_one_frame)
        self.vpos_one_top_label.setGeometry(QtCore.QRect(3, 3, 75, 16))
        self.vpos_one_top_label.setStyleSheet(_fromUtf8("border: 0;\n"
                                                        ""))
        self.vpos_one_top_label.setObjectName(_fromUtf8("vpos_one_top_label"))
        self.vpos_one_slider = QtGui.QSlider(self.vpos_one_frame)
        self.vpos_one_slider.setGeometry(QtCore.QRect(29, 23, 19, 131))
        self.vpos_one_slider.setStyleSheet(_fromUtf8("border: 0;\n"
                                                     ""))
        self.vpos_one_slider.setMinimum(-300)
        self.vpos_one_slider.setMaximum(300)
        self.vpos_one_slider.setOrientation(QtCore.Qt.Vertical)
        self.vpos_one_slider.setObjectName(_fromUtf8("vpos_one_slider"))

        self.vpos_one_center_button = QtGui.QPushButton(self.channel_one_box)
        self.vpos_one_center_button.setGeometry(QtCore.QRect(60, 128, 30, 20))
        self.vpos_one_center_button.setStyleSheet(_fromUtf8(""))
        self.vpos_one_center_button.setObjectName(_fromUtf8("vpos_one_center_button"))

        self.vpos_one_value_label = QtGui.QLabel(self.vpos_one_frame)
        self.vpos_one_value_label.setGeometry(QtCore.QRect(20, 160, 46, 13))
        self.vpos_one_value_label.setStyleSheet(_fromUtf8("border:0;"))
        self.vpos_one_value_label.setObjectName(_fromUtf8("vpos_one_value_label"))
        self.vscale_one_box = QtGui.QGroupBox(self.channel_one_box)
        self.vscale_one_box.setGeometry(QtCore.QRect(100, 50, 105, 100))
        self.vscale_one_box.setObjectName(_fromUtf8("vscale_one_box"))
        self.vscale_one_select = QtGui.QComboBox(self.vscale_one_box)
        self.vscale_one_select.setGeometry(QtCore.QRect(10, 20, 69, 20))
        self.vscale_one_select.setObjectName(_fromUtf8("vscale_one_select"))
        self.vscale_one_select.addItem(_fromUtf8(""))
        self.vscale_one_select.addItem(_fromUtf8(""))
        self.vscale_one_select.addItem(_fromUtf8(""))
        self.vscale_one_select.addItem(_fromUtf8(""))
        self.vscale_one_select.addItem(_fromUtf8(""))
        self.vscale_one_select.addItem(_fromUtf8(""))
        self.vscale_one_select.addItem(_fromUtf8(""))
        self.vscale_one_select.addItem(_fromUtf8(""))
        self.vscale_one_select.addItem(_fromUtf8(""))
        self.vscale_one_select.addItem(_fromUtf8(""))
        self.probe_one_label = QtGui.QLabel(self.vscale_one_box)
        self.probe_one_label.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.probe_one_label.setObjectName(_fromUtf8("probe_one_label"))
        self.probe_one_1_1 = QtGui.QRadioButton(self.vscale_one_box)
        self.probe_one_1_1.setGeometry(QtCore.QRect(10, 70, 41, 17))
        self.probe_one_1_1.setObjectName(_fromUtf8("probe_one_1_1"))
        self.probe_one_1_1.setChecked(True)
        self.probe_one_1_10 = QtGui.QRadioButton(self.vscale_one_box)
        self.probe_one_1_10.setGeometry(QtCore.QRect(50, 70, 41, 17))
        self.probe_one_1_10.setObjectName(_fromUtf8("probe_one_1_10"))
        self.sps_one_box = QtGui.QGroupBox(self.channel_one_box)
        self.sps_one_box.setGeometry(QtCore.QRect(100, 160, 105, 71))
        self.sps_one_box.setObjectName(_fromUtf8("sps_one_box"))
        self.sps_one_label = QtGui.QLabel(self.sps_one_box)
        self.sps_one_label.setGeometry(QtCore.QRect(10, 20, 85, 45))
        self.sps_one_label.setObjectName(_fromUtf8("sps_one_label"))
        self.sps_one_label.setWordWrap(True)

        '''
        CHANNEL 2.
        '''
        self.channel_two_box = QtGui.QGroupBox(self.channel_control_box)
        self.channel_two_box.setGeometry(QtCore.QRect(10, 270, 211, 240))
        self.channel_two_box.setObjectName(_fromUtf8("channel_two_box"))
        self.ch2_checkbox = QtGui.QCheckBox(self.channel_two_box)
        self.ch2_checkbox.setGeometry(QtCore.QRect(10, 20, 140, 20))
        self.ch2_checkbox.setObjectName(_fromUtf8("ch2_checkbox"))
        self.ch2_checkbox.setStyleSheet(_fromUtf8("background-color: #f11;\n"
                                                  "border: 1px solid #000;\n"
                                                  "border-radius: 3px;\n" "padding: 30px 0 30px 5px;"))
        self.ch2_checkbox.setChecked(False)
        self.vpos_two_frame = QtGui.QFrame(self.channel_two_box)
        self.vpos_two_frame.setGeometry(QtCore.QRect(10, 50, 81, 181))
        self.vpos_two_frame.setStyleSheet(_fromUtf8("background-color: #eef;\n"
                                                    "border: 1px solid #888;\n"
                                                    "border-radius: 5px;"))
        self.vpos_two_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.vpos_two_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.vpos_two_frame.setObjectName(_fromUtf8("vpos_two_frame"))
        self.vpos_two_top_label = QtGui.QLabel(self.vpos_two_frame)
        self.vpos_two_top_label.setGeometry(QtCore.QRect(3, 3, 75, 16))
        self.vpos_two_top_label.setStyleSheet(_fromUtf8("border: 0;\n"
                                                        ""))
        self.vpos_two_top_label.setObjectName(_fromUtf8("vpos_two_top_label"))
        self.vpos_two_slider = QtGui.QSlider(self.vpos_two_frame)
        self.vpos_two_slider.setGeometry(QtCore.QRect(29, 23, 19, 131))
        self.vpos_two_slider.setStyleSheet(_fromUtf8("border: 0;\n"
                                                     ""))
        self.vpos_two_slider.setMinimum(-300)
        self.vpos_two_slider.setMaximum(300)
        self.vpos_two_slider.setOrientation(QtCore.Qt.Vertical)
        self.vpos_two_slider.setObjectName(_fromUtf8("vpos_two_slider"))

        self.vpos_two_center_button = QtGui.QPushButton(self.channel_two_box)
        self.vpos_two_center_button.setGeometry(QtCore.QRect(60, 128, 30, 20))
        self.vpos_two_center_button.setStyleSheet(_fromUtf8(""))
        self.vpos_two_center_button.setObjectName(_fromUtf8("vpos_one_center_button"))

        self.vpos_two_value_label = QtGui.QLabel(self.vpos_two_frame)
        self.vpos_two_value_label.setGeometry(QtCore.QRect(20, 160, 46, 13))
        self.vpos_two_value_label.setStyleSheet(_fromUtf8("border:0;"))
        self.vpos_two_value_label.setObjectName(_fromUtf8("vpos_two_value_label"))
        self.vscale_two_box = QtGui.QGroupBox(self.channel_two_box)
        self.vscale_two_box.setGeometry(QtCore.QRect(100, 50, 105, 100))
        self.vscale_two_box.setObjectName(_fromUtf8("vscale_two_box"))
        self.vscale_two_select = QtGui.QComboBox(self.vscale_two_box)
        self.vscale_two_select.setGeometry(QtCore.QRect(10, 20, 69, 20))
        self.vscale_two_select.setObjectName(_fromUtf8("vscale_two_select"))
        self.vscale_two_select.addItem(_fromUtf8(""))
        self.vscale_two_select.addItem(_fromUtf8(""))
        self.vscale_two_select.addItem(_fromUtf8(""))
        self.vscale_two_select.addItem(_fromUtf8(""))
        self.vscale_two_select.addItem(_fromUtf8(""))
        self.vscale_two_select.addItem(_fromUtf8(""))
        self.vscale_two_select.addItem(_fromUtf8(""))
        self.vscale_two_select.addItem(_fromUtf8(""))
        self.vscale_two_select.addItem(_fromUtf8(""))
        self.vscale_two_select.addItem(_fromUtf8(""))
        self.probe_two_label = QtGui.QLabel(self.vscale_two_box)
        self.probe_two_label.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.probe_two_label.setObjectName(_fromUtf8("probe_two_label"))
        self.probe_two_1_1 = QtGui.QRadioButton(self.vscale_two_box)
        self.probe_two_1_1.setGeometry(QtCore.QRect(10, 70, 41, 17))
        self.probe_two_1_1.setObjectName(_fromUtf8("probe_two_1_1"))
        self.probe_two_1_1.setChecked(True)
        self.probe_two_1_10 = QtGui.QRadioButton(self.vscale_two_box)
        self.probe_two_1_10.setGeometry(QtCore.QRect(50, 70, 41, 17))
        self.probe_two_1_10.setObjectName(_fromUtf8("probe_two_1_10"))
        self.sps_two_box = QtGui.QGroupBox(self.channel_two_box)
        self.sps_two_box.setGeometry(QtCore.QRect(100, 160, 105, 71))
        self.sps_two_box.setObjectName(_fromUtf8("sps_two_box"))
        self.sps_two_label = QtGui.QLabel(self.sps_two_box)
        self.sps_two_label.setGeometry(QtCore.QRect(10, 20, 85, 45))
        self.sps_two_label.setObjectName(_fromUtf8("sps_two_label"))
        self.sps_two_label.setWordWrap(True)
        self.channel_one_box.raise_()
        self.vscale_one_box.raise_()
        self.channel_two_box.raise_()

        '''
        Functions.
        '''
        self.functions_box = QtGui.QGroupBox(self.centralwidget)
        self.functions_box.setGeometry(QtCore.QRect(1005, 0, 230, 130))
        self.functions_box.setObjectName(_fromUtf8("functions_box"))
        self.run_button = QtGui.QPushButton(self.functions_box)
        self.run_button.setGeometry(QtCore.QRect(10, 20, 65, 23))
        self.run_button.setCheckable(True)
        self.run_button.setObjectName(_fromUtf8("run_button"))
        self.logic_button = QtGui.QPushButton(self.functions_box)
        self.logic_button.setGeometry(QtCore.QRect(10, 85, 65, 23))
        self.logic_button.setCheckable(True)
        self.logic_button.setObjectName(_fromUtf8("logic_button"))
        self.logic_settings_button = QtGui.QPushButton(self.functions_box)
        self.logic_settings_button.setGeometry(QtCore.QRect(75, 85, 23, 23))
        self.logic_settings_button.setObjectName(_fromUtf8("logic_settings_button"))
        self.clear_button = QtGui.QPushButton(self.functions_box)
        self.clear_button.setGeometry(QtCore.QRect(80, 50, 65, 23))
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.single_button = QtGui.QPushButton(self.functions_box)
        self.single_button.setGeometry(QtCore.QRect(80, 20, 65, 23))
        self.single_button.setObjectName(_fromUtf8("single_button"))
        self.FFT_button = QtGui.QPushButton(self.functions_box)
        self.FFT_button.setGeometry(QtCore.QRect(160, 20, 65, 23))
        self.FFT_button.setObjectName(_fromUtf8("FFT_button"))
        self.acquisition_button = QtGui.QPushButton(self.functions_box)
        self.acquisition_button.setGeometry(QtCore.QRect(160, 50, 65, 23))
        self.acquisition_button.setObjectName(_fromUtf8("acquisition_button"))

        '''
        Horizontal
        '''

        self.hscale_box = QtGui.QGroupBox(self.centralwidget)
        self.hscale_box.setGeometry(QtCore.QRect(1240, 0, 120, 130))
        self.hscale_box.setObjectName(_fromUtf8("hscale_box"))
        self.hscale_select = QtGui.QComboBox(self.hscale_box)
        self.hscale_select.setGeometry(QtCore.QRect(10, 20, 73, 20))
        self.hscale_select.setObjectName(_fromUtf8("hscale_select"))
        self.hscale_select.addItem(_fromUtf8("100ns/div"), 0.0000001)
        self.hscale_select.addItem(_fromUtf8("200ns/div"), 0.0000002)
        self.hscale_select.addItem(_fromUtf8("500ns/div"), 0.0000005)
        self.hscale_select.addItem(_fromUtf8("1us/div"), 0.000001)
        self.hscale_select.addItem(_fromUtf8("2us/div"), 0.000002)
        self.hscale_select.addItem(_fromUtf8("5us/div"), 0.000005)
        self.hscale_select.addItem(_fromUtf8("10us/div"), 0.00001)
        self.hscale_select.addItem(_fromUtf8("20us/div"), 0.00002)
        self.hscale_select.addItem(_fromUtf8("50us/div"), 0.00005)
        self.hscale_select.addItem(_fromUtf8("100us/div"), 0.0001)
        self.hscale_select.addItem(_fromUtf8("200us/div"), 0.0002)
        self.hscale_select.addItem(_fromUtf8("500us/div"), 0.0005)
        self.hscale_select.addItem(_fromUtf8("1ms/div"), 0.001)
        self.hscale_select.addItem(_fromUtf8("2ms/div"), 0.002)
        self.hscale_select.addItem(_fromUtf8("5ms/div"), 0.005)
        self.hscale_select.addItem(_fromUtf8("10ms/div"), 0.01)
        self.hscale_select.addItem(_fromUtf8("20ms/div"), 0.02)
        self.hscale_select.addItem(_fromUtf8("50ms/div"), 0.05)
        self.hscale_select.addItem(_fromUtf8("100ms/div"), 0.1)
        self.hscale_select.addItem(_fromUtf8("200ms/div"), 0.2)
        self.hscale_select.addItem(_fromUtf8("500ms/div"), 0.5)
        self.hscale_select.addItem(_fromUtf8("1s/div"), 1.0)
        self.hscale_select.setMaxVisibleItems(22)
        self.xy_button = QtGui.QPushButton(self.hscale_box)
        self.xy_button.setGeometry(QtCore.QRect(10, 50, 65, 23))
        self.xy_button.setCheckable(True)
        self.xy_button.setEnabled(False)
        self.xy_button.setObjectName(_fromUtf8("xy_button"))

        '''
        Trigger.
        '''
        self.trigger_box = QtGui.QGroupBox(self.centralwidget)
        self.trigger_box.setGeometry(QtCore.QRect(1240, 135, 120, 521))
        self.trigger_box.setObjectName(_fromUtf8("trigger_box"))
        self.show_button = QtGui.QPushButton(self.trigger_box)
        self.show_button.setGeometry(QtCore.QRect(22, 35, 75, 23))
        self.show_button.setObjectName(_fromUtf8("show_button"))
        self.show_button.setCheckable(True)
        self.trigger_level_frame = QtGui.QFrame(self.trigger_box)
        self.trigger_level_frame.setGeometry(QtCore.QRect(22, 70, 75, 181))
        self.trigger_level_frame.setStyleSheet(_fromUtf8("background-color: #84F59E;\n"
                                                         "border: 1px solid #888;\n"
                                                         "border-radius: 5px;"))
        self.trigger_level_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.trigger_level_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.trigger_level_frame.setObjectName(_fromUtf8("trigger_level_frame"))
        self.trigger_level_label = QtGui.QLabel(self.trigger_level_frame)
        self.trigger_level_label.setGeometry(QtCore.QRect(8, 3, 60, 16))
        self.trigger_level_label.setStyleSheet(_fromUtf8("border: 0;\n"
                                                         ""))
        self.trigger_level_label.setObjectName(_fromUtf8("trigger_level_label"))
        self.trigger_level_slider = QtGui.QSlider(self.trigger_level_frame)
        self.trigger_level_slider.setGeometry(QtCore.QRect(29, 23, 19, 131))
        self.trigger_level_slider.setStyleSheet(_fromUtf8("border: 0;\n"
                                                          ""))
        self.trigger_level_slider.setMinimum(-400)
        self.trigger_level_slider.setMaximum(400)
        self.trigger_level_slider.setOrientation(QtCore.Qt.Vertical)
        self.trigger_level_slider.setObjectName(_fromUtf8("trigger_level_slider"))
        self.trigger_level_value_label = QtGui.QLabel(self.trigger_level_frame)
        self.trigger_level_value_label.setGeometry(QtCore.QRect(29, 160, 35, 13))
        self.trigger_level_value_label.setStyleSheet(_fromUtf8("border:0;"))
        self.trigger_level_value_label.setObjectName(_fromUtf8("trigger_level_value_label"))

        self.trigger_source_label = QtGui.QLabel(self.trigger_box)
        self.trigger_source_label.setGeometry(QtCore.QRect(22, 270, 35, 13))
        self.trigger_source_label.setObjectName(_fromUtf8("trigger_source_label"))
        self.trigger_source_ch1 = QtGui.QRadioButton(self.trigger_box)
        self.trigger_source_ch1.setGeometry(QtCore.QRect(22, 290, 41, 17))
        self.trigger_source_ch1.setObjectName(_fromUtf8("trigger_source_ch1"))
        self.trigger_source_ch1.setChecked(True)
        self.trigger_source_ch2 = QtGui.QRadioButton(self.trigger_box)
        self.trigger_source_ch2.setGeometry(QtCore.QRect(22, 320, 41, 17))
        self.trigger_source_ch2.setObjectName(_fromUtf8("trigger_source_ch2"))

        self.holdoff_label = QtGui.QLabel(self.trigger_box)
        self.holdoff_label.setGeometry(QtCore.QRect(22, 360, 45, 13))
        self.holdoff_label.setObjectName(_fromUtf8("trigger_source_label"))
        self.holdoff_spinBox = QtGui.QDoubleSpinBox(self.trigger_box)
        self.holdoff_spinBox.setGeometry(QtCore.QRect(22, 380, 81, 22))
        self.holdoff_spinBox.setMinimum(0.9)
        self.holdoff_spinBox.setMaximum(1000)
        self.holdoff_spinBox.setSingleStep(0.1)
        self.holdoff_spinBox.setSuffix("ns")
        self.holdoff_spinBox.setDecimals(1)
        self.holdoff_spinBox.setObjectName(_fromUtf8("spinBox"))

        '''
        Other configs.
        '''
        self.plot.raise_()
        self.readout_frame.raise_()
        self.channel_one_box.raise_()
        self.horizontal_scroll_bar.raise_()
        self.channel_control_box.raise_()
        self.functions_box.raise_()
        self.trigger_box.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave_as = QtGui.QMenu(self.menuFile)
        self.menuSave_as.setObjectName(_fromUtf8("menuSave_as"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSignal = QtGui.QAction(MainWindow)
        self.actionSignal.setObjectName(_fromUtf8("actionSignal"))
        self.actionPNG = QtGui.QAction(MainWindow)
        self.actionPNG.setObjectName(_fromUtf8("actionPNG"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuSave_as.addAction(self.actionSignal)
        self.menuSave_as.addAction(self.actionPNG)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuSave_as.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.actionTest_connection = QtGui.QAction(MainWindow)
        self.actionTest_connection.setObjectName(_fromUtf8("actionTest_connection"))
        self.menuDevice = QtGui.QMenu(self.menubar)
        self.menuDevice.setObjectName(_fromUtf8("menuDevice"))
        self.menuDevice.addAction(self.actionTest_connection)
        self.actionView_help = QtGui.QAction(MainWindow)
        self.actionView_help.setObjectName(_fromUtf8("actionView_help"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuHelp.addAction(self.actionView_help)
        self.menuHelp.addAction(self.actionAbout)
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.hscale_select.setCurrentIndex(8)
        self.vscale_one_select.setCurrentIndex(7)
        self.vscale_two_select.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "DSO Thesis - Artem Kolichenkov", None))
        self.readout_special_one.setText(_translate("MainWindow", "CH1_max_freq = 800 Hz", None))
        self.readout_special_two.setText(_translate("MainWindow", "CH2_max_freq = 800 Hz", None))
        self.readout_one.setText(_translate("MainWindow", "CH1_Vpp:", None))
        self.readout_two.setText(_translate("MainWindow", "CH1_Freq:", None))
        self.readout_three.setText(_translate("MainWindow", "CH1_Vrms:", None))
        self.readout_four.setText(_translate("MainWindow", "CH1_Vmax:", None))
        self.readout_five.setText(_translate("MainWindow", "CH2_Vpp:", None))
        self.readout_six.setText(_translate("MainWindow", "CH2_Freq:", None))
        self.readout_seven.setText(_translate("MainWindow", "CH2_Vrms:", None))
        self.readout_eight.setText(_translate("MainWindow", "CH2_Vmax:", None))
        self.channel_control_box.setTitle(_translate("MainWindow", "Channel control", None))
        self.channel_one_box.setTitle(_translate("MainWindow", "CH1", None))
        self.ch1_checkbox.setText(_translate("MainWindow", "Turn on channel 1", None))
        self.vpos_one_top_label.setText(_translate("MainWindow", "Vertical position", None))
        self.vpos_one_value_label.setText(_translate("MainWindow", "0.0 div", None))
        self.vscale_one_box.setTitle(_translate("MainWindow", "Vertical scale", None))
        self.vscale_one_select.setItemText(0, _translate("MainWindow", "5mV/div", None))
        self.vscale_one_select.setItemText(1, _translate("MainWindow", "10mV/div", None))
        self.vscale_one_select.setItemText(2, _translate("MainWindow", "20mV/div", None))
        self.vscale_one_select.setItemText(3, _translate("MainWindow", "50mV/div", None))
        self.vscale_one_select.setItemText(4, _translate("MainWindow", "100mV/div", None))
        self.vscale_one_select.setItemText(5, _translate("MainWindow", "200mV/div", None))
        self.vscale_one_select.setItemText(6, _translate("MainWindow", "500mV/div", None))
        self.vscale_one_select.setItemText(7, _translate("MainWindow", "1V/div", None))
        self.vscale_one_select.setItemText(8, _translate("MainWindow", "2V/div", None))
        self.vscale_one_select.setItemText(9, _translate("MainWindow", "5V/div", None))
        self.probe_one_label.setText(_translate("MainWindow", "Probe:", None))
        self.holdoff_label.setText(_translate("MainWindow", "Holdoff:", None))
        self.probe_one_1_1.setText(_translate("MainWindow", "1:1", None))
        self.probe_one_1_10.setText(_translate("MainWindow", "1:10", None))

        self.sps_one_box.setTitle(_translate("MainWindow", "Max Frequency", None))
        self.hscale_box.setTitle(_translate("MainWindow", "Horizontal scale", None))
        self.sps_one_label.setText(_translate("MainWindow", "~1 MHz", None))
        self.trigger_level_label.setText(_translate("MainWindow", "Trigger level", None))
        self.trigger_level_value_label.setText(_translate("MainWindow", "0 V", None))
        self.trigger_source_label.setText(_translate("MainWindow", "Source:", None))
        self.channel_two_box.setTitle(_translate("MainWindow", "CH2", None))
        self.ch2_checkbox.setText(_translate("MainWindow", "Turn on channel 2", None))
        self.vpos_two_top_label.setText(_translate("MainWindow", "Vertical position", None))
        self.vpos_two_value_label.setText(_translate("MainWindow", "0.0 div", None))
        self.vscale_two_box.setTitle(_translate("MainWindow", "Vertical scale", None))
        self.vscale_two_select.setItemText(0, _translate("MainWindow", "5mV/div", None))
        self.vscale_two_select.setItemText(1, _translate("MainWindow", "10mV/div", None))
        self.vscale_two_select.setItemText(2, _translate("MainWindow", "20mV/div", None))
        self.vscale_two_select.setItemText(3, _translate("MainWindow", "50mV/div", None))
        self.vscale_two_select.setItemText(4, _translate("MainWindow", "100mV/div", None))
        self.vscale_two_select.setItemText(5, _translate("MainWindow", "200mV/div", None))
        self.vscale_two_select.setItemText(6, _translate("MainWindow", "500mV/div", None))
        self.vscale_two_select.setItemText(7, _translate("MainWindow", "1V/div", None))
        self.vscale_two_select.setItemText(8, _translate("MainWindow", "2V/div", None))
        self.vscale_two_select.setItemText(9, _translate("MainWindow", "5V/div", None))
        self.probe_two_label.setText(_translate("MainWindow", "Probe:", None))
        self.probe_two_1_1.setText(_translate("MainWindow", "1:1", None))
        self.probe_two_1_10.setText(_translate("MainWindow", "1:10", None))
        self.trigger_source_ch1.setText(_translate("MainWindow", "CH1", None))
        self.trigger_source_ch2.setText(_translate("MainWindow", "CH2", None))
        self.sps_two_box.setTitle(_translate("MainWindow", "Max Frequency", None))
        self.sps_two_label.setText(_translate("MainWindow", "~1 MHz", None))
        self.functions_box.setTitle(_translate("MainWindow", "Functions", None))
        self.run_button.setText(_translate("MainWindow", "Run", None))
        self.logic_button.setText(_translate("MainWindow", "Logic OFF", None))
        self.clear_button.setText(_translate("MainWindow", "Clear", None))
        self.single_button.setText(_translate("MainWindow", "Single shot", None))
        self.FFT_button.setText(_translate("MainWindow", "FFT", None))
        self.acquisition_button.setText(_translate("MainWindow", "Acquisition", None))
        self.xy_button.setText(_translate("MainWindow", "XY mode", None))
        self.vpos_one_center_button.setText(_translate("MainWindow", "< 0", None))
        self.vpos_two_center_button.setText(_translate("MainWindow", "< 0", None))
        self.show_button.setText(_translate("MainWindow", "Show", None))
        self.trigger_box.setTitle(_translate("MainWindow", "Trigger", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSave_as.setTitle(_translate("MainWindow", "Save as", None))
        self.menuDevice.setTitle(_translate("MainWindow", "Device", None))
        self.actionTest_connection.setText(_translate("MainWindow", "Test connection", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionView_help.setText(_translate("MainWindow", "View help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSignal.setText(_translate("MainWindow", "Signal", None))
        self.actionPNG.setText(_translate("MainWindow", "PNG", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))


class Ui_LogicDialog(object):
    def setupUi(self, LogicDialog):
        LogicDialog.setObjectName(_fromUtf8("LogicDialog"))
        LogicDialog.resize(224, 300)
        self.logic0_checkbox = QtGui.QCheckBox(LogicDialog)
        self.logic0_checkbox.setGeometry(QtCore.QRect(10, 40, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logic0_checkbox.setFont(font)
        self.logic0_checkbox.setChecked(True)
        self.logic0_checkbox.setObjectName(_fromUtf8("logic0_checkbox"))
        self.logic1_checkbox = QtGui.QCheckBox(LogicDialog)
        self.logic1_checkbox.setGeometry(QtCore.QRect(10, 70, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logic1_checkbox.setFont(font)
        self.logic1_checkbox.setChecked(True)
        self.logic1_checkbox.setObjectName(_fromUtf8("logic1_checkbox"))
        self.logic2_checkbox = QtGui.QCheckBox(LogicDialog)
        self.logic2_checkbox.setGeometry(QtCore.QRect(10, 100, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logic2_checkbox.setFont(font)
        self.logic2_checkbox.setChecked(True)
        self.logic2_checkbox.setObjectName(_fromUtf8("logic2_checkbox"))
        self.logic3_checkbox = QtGui.QCheckBox(LogicDialog)
        self.logic3_checkbox.setGeometry(QtCore.QRect(10, 130, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logic3_checkbox.setFont(font)
        self.logic3_checkbox.setChecked(True)
        self.logic3_checkbox.setObjectName(_fromUtf8("logic3_checkbox"))
        self.logic4_checkbox = QtGui.QCheckBox(LogicDialog)
        self.logic4_checkbox.setGeometry(QtCore.QRect(10, 160, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logic4_checkbox.setFont(font)
        self.logic4_checkbox.setChecked(True)
        self.logic4_checkbox.setObjectName(_fromUtf8("logic4_checkbox"))
        self.logic5_checkbox = QtGui.QCheckBox(LogicDialog)
        self.logic5_checkbox.setGeometry(QtCore.QRect(10, 190, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logic5_checkbox.setFont(font)
        self.logic5_checkbox.setChecked(True)
        self.logic5_checkbox.setObjectName(_fromUtf8("logic5_checkbox"))
        self.logic6_checkbox = QtGui.QCheckBox(LogicDialog)
        self.logic6_checkbox.setGeometry(QtCore.QRect(10, 220, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logic6_checkbox.setFont(font)
        self.logic6_checkbox.setChecked(True)
        self.logic6_checkbox.setObjectName(_fromUtf8("logic6_checkbox"))
        self.logic7_checkbox = QtGui.QCheckBox(LogicDialog)
        self.logic7_checkbox.setGeometry(QtCore.QRect(10, 250, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logic7_checkbox.setFont(font)
        self.logic7_checkbox.setChecked(True)
        self.logic7_checkbox.setObjectName(_fromUtf8("logic7_checkbox"))
        self.logic_color_label_0 = QtGui.QLabel(LogicDialog)
        self.logic_color_label_0.setGeometry(QtCore.QRect(160, 40, 31, 27))
        self.logic_color_label_0.setStyleSheet(
            _fromUtf8("background-color:white; border:1px solid"))
        self.logic_color_label_0.setText(_fromUtf8(""))
        self.logic_color_label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.logic_color_label_0.setObjectName(_fromUtf8("logic_color_label_0"))
        self.logic_color_label_1 = QtGui.QLabel(LogicDialog)
        self.logic_color_label_1.setGeometry(QtCore.QRect(160, 70, 31, 27))
        self.logic_color_label_1.setStyleSheet(
            _fromUtf8("background-color:yellow; border:1px solid"))
        self.logic_color_label_1.setText(_fromUtf8(""))
        self.logic_color_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.logic_color_label_1.setObjectName(_fromUtf8("logic_color_label_1"))
        self.logic_color_label_2 = QtGui.QLabel(LogicDialog)
        self.logic_color_label_2.setGeometry(QtCore.QRect(160, 100, 31, 27))
        self.logic_color_label_2.setStyleSheet(_fromUtf8("background-color:lime; border:1px solid"))
        self.logic_color_label_2.setText(_fromUtf8(""))
        self.logic_color_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.logic_color_label_2.setObjectName(_fromUtf8("logic_color_label_2"))
        self.logic_color_label_3 = QtGui.QLabel(LogicDialog)
        self.logic_color_label_3.setGeometry(QtCore.QRect(160, 130, 31, 27))
        self.logic_color_label_3.setStyleSheet(_fromUtf8("background-color:blue; border:1px solid"))
        self.logic_color_label_3.setText(_fromUtf8(""))
        self.logic_color_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.logic_color_label_3.setObjectName(_fromUtf8("logic_color_label_3"))
        self.logic_color_label_4 = QtGui.QLabel(LogicDialog)
        self.logic_color_label_4.setGeometry(QtCore.QRect(160, 160, 31, 27))
        self.logic_color_label_4.setStyleSheet(
            _fromUtf8("background-color:magenta; border:1px solid"))
        self.logic_color_label_4.setText(_fromUtf8(""))
        self.logic_color_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.logic_color_label_4.setObjectName(_fromUtf8("logic_color_label_4"))
        self.logic_color_label_5 = QtGui.QLabel(LogicDialog)
        self.logic_color_label_5.setGeometry(QtCore.QRect(160, 190, 31, 27))
        self.logic_color_label_5.setStyleSheet(_fromUtf8("background-color:red; border:1px solid"))
        self.logic_color_label_5.setText(_fromUtf8(""))
        self.logic_color_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.logic_color_label_5.setObjectName(_fromUtf8("logic_color_label_5"))
        self.logic_color_label_6 = QtGui.QLabel(LogicDialog)
        self.logic_color_label_6.setGeometry(QtCore.QRect(160, 220, 31, 27))
        self.logic_color_label_6.setStyleSheet(_fromUtf8("background-color:cyan; border:1px solid"))
        self.logic_color_label_6.setText(_fromUtf8(""))
        self.logic_color_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.logic_color_label_6.setObjectName(_fromUtf8("logic_color_label_6"))
        self.logic_color_label_7 = QtGui.QLabel(LogicDialog)
        self.logic_color_label_7.setGeometry(QtCore.QRect(160, 250, 31, 27))
        self.logic_color_label_7.setStyleSheet(
            _fromUtf8("background-color:orange; border:1px solid"))
        self.logic_color_label_7.setText(_fromUtf8(""))
        self.logic_color_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.logic_color_label_7.setObjectName(_fromUtf8("logic_color_label_7"))

        self.retranslateUi(LogicDialog)

    def retranslateUi(self, LogicDialog):
        LogicDialog.setWindowTitle(_translate("LogicDialog", "Logic channels settings", None))
        self.logic0_checkbox.setText(_translate("LogicDialog", "logic channel 0", None))
        self.logic1_checkbox.setText(_translate("LogicDialog", "logic channel 1", None))
        self.logic2_checkbox.setText(_translate("LogicDialog", "logic channel 2", None))
        self.logic3_checkbox.setText(_translate("LogicDialog", "logic channel 3", None))
        self.logic4_checkbox.setText(_translate("LogicDialog", "logic channel 4", None))
        self.logic5_checkbox.setText(_translate("LogicDialog", "logic channel 5", None))
        self.logic6_checkbox.setText(_translate("LogicDialog", "logic channel 6", None))
        self.logic7_checkbox.setText(_translate("LogicDialog", "logic channel 7", None))


class Ui_FFTDialog(object):
    def setupUi(self, FFTDialog):
        FFTDialog.setObjectName(_fromUtf8("FFTDialog"))
        FFTDialog.resize(900, 622)
        FFTDialog.setStyleSheet("background-color: #000")
        self.fft_plot = PlotWidget(parent=self)
        self.fft_plot.setGeometry(QtCore.QRect(0, 22, 900, 600))
        self.fft_plot.setObjectName(_fromUtf8("fft_plot"))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.freq_label = QtGui.QLabel(text="-----", parent=FFTDialog)
        self.freq_label.setGeometry(QtCore.QRect(750, 0, 140, 22))
        self.freq_label.setFont(font)
        self.freq_label.setStyleSheet(
            _fromUtf8("color: #fff"))
        self.retranslateUi(FFTDialog)

    def retranslateUi(self, FFTDialog):
        FFTDialog.setWindowTitle(_translate("FFTDialog", "FFT", None))
